Bootstrap/README.md
=> Updated Bootstrap readme.md file

Bootstrap/MVC/Scripts/SearchBox/Search-box.js, Bootstrap/MVC/Views/Layouts/default.cshtml, Bootstrap/MVC/Views/SearchBox/SearchBox.cshtml, Foundation/MVC/Scripts/SearchBox/Search-box.js, Foundation/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/SearchBox/SearchBox.cshtml, SemanticUI/MVC/Scripts/SearchBox/Search-box.js, SemanticUI/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/SearchBox/SearchBox.cshtml
Reverts Sitefinity/feather-packages#35
=> Revert "Fix search hybrid"

Bootstrap/MVC/Scripts/SearchBox/Search-box.js, Bootstrap/MVC/Views/Layouts/default.cshtml, Bootstrap/MVC/Views/SearchBox/SearchBox.cshtml, Foundation/MVC/Scripts/SearchBox/Search-box.js, Foundation/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/SearchBox/SearchBox.cshtml, SemanticUI/MVC/Scripts/SearchBox/Search-box.js, SemanticUI/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/SearchBox/SearchBox.cshtml
=> Related to #147 - use ResourceHelper.GetWebResourceUrl method

Bootstrap/MVC/Views/SearchResults/SearchResults.cshtml, Foundation/MVC/Views/SearchResults/SearchResults.cshtml, SemanticUI/MVC/Views/SearchResults/SearchResults.cshtml
=> Search fixes peleva

Foundation/MVC/Views/News/Detail.DetailPage.cshtml
=> Fixes #42 Author is not displayed in foundation package

Bootstrap/client-components/fields/html-field/sf-html-field.html, Foundation/client-components/fields/html-field/sf-html-field.html, SemanticUI/client-components/fields/html-field/sf-html-field.html
=> html field image slector #56

Bootstrap/MVC/Views/ImageGallery/DesignerView.Simple.cshtml, Bootstrap/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/ImageGallery/List.ImageGallery.cshtml, Bootstrap/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, Bootstrap/MVC/Views/ImageGallery/List.SimpleList.cshtml, Bootstrap/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml
=> Merged templates changes from feather-widgets

Bootstrap/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml, Foundation/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml, SemanticUI/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml
=> Added default data back to thumbnail strip

Bootstrap/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, Bootstrap/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml, Foundation/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, Foundation/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml, SemanticUI/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, SemanticUI/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml
=> link current image

Bootstrap/MVC/Views/Layouts/default.cshtml, Bootstrap/MVC/Views/Navigation/NavigationView.Horizontal.cshtml, Bootstrap/MVC/Views/Navigation/NavigationView.Pills.cshtml, Foundation/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/Navigation/NavigationView.Horizontal.cshtml, SemanticUI/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/Navigation/NavigationView.Horizontal.cshtml
=> fix script references for navigation

Bootstrap/package.json, Foundation/package.json, SemanticUI/package.json
=> Login widgets peleva

Bootstrap/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, Foundation/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, SemanticUI/MVC/Views/ImageGallery/Detail.DetailPage.cshtml
=> fixed prev/next issue in details view of image gallery

Bootstrap/MVC/Views/ChangePassword/ChangePassword.ChangePassword.cshtml, Bootstrap/MVC/Views/LoginForm/ForgotPassword.ForgottenPassword.cshtml, Bootstrap/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, Bootstrap/MVC/Views/LoginForm/ResetPassword.ResetPassword.cshtml, Bootstrap/MVC/Views/Profile/Edit.ProfileEdit.cshtml, Bootstrap/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Moved back to login button to be next to the Registration button

Bootstrap/MVC/Views/LoginForm/ResetPassword.ResetPassword.cshtml
=> Fixed 404 error when forgotten password is reseted

Bootstrap/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/Layouts/default.cshtml
=> Fixed social share icons

Bootstrap/MVC/Views/Profile/Edit.ProfileEdit.cshtml, SemanticUI/MVC/Views/Profile/Edit.ProfileEdit.cshtml
=> fixed firefox validation issue

Bootstrap/MVC/Views/LoginForm/ForgotPassword.ForgottenPassword.cshtml
=> fixed validation display for password reset

Bootstrap/MVC/Views/ChangePassword/ChangePassword.ChangePassword.cshtml, SemanticUI/MVC/Views/ChangePassword/ChangePassword.ChangePassword.cshtml
https://github.com/Sitefinity/feather/issues/1008
=> Change password pure page fix #1008

Bootstrap/MVC/Views/Navigation/NavigationView.Horizontal.cshtml, Foundation/MVC/Views/Navigation/NavigationView.Horizontal.cshtml, SemanticUI/MVC/Views/Navigation/NavigationView.Horizontal.cshtml
=> added missing jQuery references

Bootstrap/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/Layouts/default.cshtml
=> extracted public wrapper from placeholder helper

Bootstrap/MVC/Views/Registration/Registration.RegistrationForm.cshtml, SemanticUI/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Added type email to inputs for client side email validation

Bootstrap/client-components/fields/html-field/sf-html-field.sf-cshtml, Foundation/client-components/fields/html-field/sf-html-field.sf-cshtml, SemanticUI/client-components/fields/html-field/sf-html-field.sf-cshtml
=> Added video selector icon

Bootstrap/MVC/Views/LoginForm/ResetPassword.ResetPassword.cshtml, SemanticUI/MVC/Views/LoginForm/ResetPassword.ResetPassword.cshtml
https://github.com/Sitefinity/feather-widgets/issues/624
=> Rester password fix #624

Bootstrap/MVC/Views/SearchBox/SearchBox.cshtml, Foundation/MVC/Views/SearchBox/SearchBox.cshtml, SemanticUI/MVC/Views/SearchBox/SearchBox.cshtml
=> Search box - WCAG 2.0 Level A Issue: 1.1.1 Non-text Content #504

Bootstrap/MVC/Scripts/Profile/profile-edit.js, Bootstrap/MVC/Views/ChangePassword/ChangePassword.ChangePassword.cshtml, Bootstrap/MVC/Views/LoginForm/ForgotPassword.ForgottenPassword.cshtml, Bootstrap/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, Bootstrap/MVC/Views/LoginForm/ResetPassword.ResetPassword.cshtml, Bootstrap/MVC/Views/Profile/Edit.ProfileEdit.cshtml, Bootstrap/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Removed rows and cols from templates of Login widgets (UX improvement)

Bootstrap/MVC/Scripts/Profile/profile-edit.js
=> Login widgets remove grid

Bootstrap/MVC/Views/SearchResults/SearchResults.cshtml
=> Removed unnecessary jquery scritp

Bootstrap/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/Layouts/default.cshtml
=> Inline editing attributes are not rendered if request is ajax

Foundation/MVC/Views/Navigation/Dropdown.cshtml
=> fixed sitemap template for navigation in foundation

SemanticUI/MVC/Views/ChangePassword/ChangePassword.ChangePassword.cshtml, SemanticUI/MVC/Views/LoginForm/ForgotPassword.ForgottenPassword.cshtml, SemanticUI/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, SemanticUI/MVC/Views/LoginForm/ResetPassword.ResetPassword.cshtml, SemanticUI/MVC/Views/News/List.NewsList.cshtml, SemanticUI/MVC/Views/Profile/Edit.ProfileEdit.cshtml, SemanticUI/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Semantic login improvements

Bootstrap/MVC/Views/VideoGallery/List.VideoGallery.cshtml
Fixed: VideoGallery > Bootstrap template - the paging doesn't look fine #1433
=> Video gallery styles

Bootstrap/MVC/Views/BlogPost/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/BlogPost/List.BlogPostList.cshtml
=> Added templates for Blog post widget

Bootstrap/MVC/Views/VideoGallery/Detail.Default.cshtml
=> Fixed aspect ratio in Bottstrap

Bootstrap/MVC/Views/Blog/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/Blog/List.BlogList.cshtml
=> Added Blog list templates

Bootstrap/MVC/Views/Blog/Detail.DetailPage.cshtml
=> Post populating of blogs count added

Bootstrap/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, Bootstrap/MVC/Views/Profile/Edit.ProfileEdit.cshtml, Bootstrap/MVC/Views/Registration/Registration.RegistrationForm.cshtml, SemanticUI/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, SemanticUI/MVC/Views/Profile/Edit.ProfileEdit.cshtml, SemanticUI/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Updated  aspnetcdn links to load based on the current scheme

Bootstrap/MVC/Views/UsersList/Detail.UserDetails.cshtml
=> Fixed class attribute

Bootstrap/MVC/Views/SearchBox/SearchBox.cshtml, Foundation/MVC/Views/SearchBox/SearchBox.cshtml, SemanticUI/MVC/Views/SearchBox/SearchBox.cshtml
=> Changed script registration for search box widget views

Bootstrap/MVC/Views/News/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/News/List.NewsList.cshtml, Foundation/MVC/Views/News/Detail.DetailPage.cshtml, Foundation/MVC/Views/News/List.NewsList.cshtml, SemanticUI/MVC/Views/News/Detail.DetailPage.cshtml, SemanticUI/MVC/Views/News/List.NewsList.cshtml
=> comments in news

Bootstrap/MVC/Views/News/List.NewsList.cshtml, Foundation/MVC/Views/News/List.NewsList.cshtml, SemanticUI/MVC/Views/News/List.NewsList.cshtml
=> fix news list

Bootstrap/MVC/Views/Navigation/NavigationView.Sitemap.cshtml, Foundation/MVC/Views/Navigation/NavigationView.Sitemap.cshtml, SemanticUI/MVC/Views/Navigation/NavigationView.Sitemap.cshtml
=> Replaced b with strong in navigation.sitemap template

Bootstrap/MVC/Views/SearchBox/SearchBox.cshtml
=> Fix for #427 - Search box - Implement default message in Bootstrap

Bootstrap/MVC/Views/Comments/Comments.Default.cshtml
=> Fixed comments script path

Bootstrap/MVC/Views/Comments/Comments.Default.cshtml
=> Add style to initially hide name and email fields

Bootstrap/MVC/Views/Comments/Comments.Default.cshtml
=> Commens styles

Bootstrap/MVC/Views/Reviews/Reviews.Default.cshtml
=> Reviews styles

Bootstrap/MVC/Views/Reviews/ReviewsCount.Default.cshtml
=> Removed anchor from list-rating-wrapper

Bootstrap/MVC/Views/Reviews/Reviews.Default.cshtml
=> Reviews count and average hidden.

Bootstrap/MVC/Views/Lists/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/Lists/List.PagesList.cshtml
=> Comments list impl

Bootstrap/MVC/Views/BlogPost/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/BlogPost/List.BlogPostList.cshtml
=> Added comments/reviews to blog posts

Bootstrap/MVC/Views/StyleSheet/Index.cshtml
=> Added styles for Index view of Css widget

Bootstrap/MVC/Views/HierarchicalTaxonomy/HierarchicalTaxonomy.CategoriesList.cshtml
=> Added Categories template to Bootstrap

Bootstrap/MVC/Views/VideoGallery/List.VideoGallery.cshtml
=> Fixed jQuery reference section

Foundation/MVC/Views/SearchResults/SearchResults.cshtml
=> fix minor issue

Bootstrap/client-components/fields/html-field/sf-html-field.sf-cshtml, Foundation/client-components/fields/html-field/sf-html-field.sf-cshtml, SemanticUI/client-components/fields/html-field/sf-html-field.sf-cshtml
=> Switched places of html mode and show/hide tools icon

Bootstrap/MVC/Views/LanguageSelector/LanguageSelector.DropDownMenu.cshtml, Bootstrap/MVC/Views/LanguageSelector/LanguageSelector.LanguageLinks.cshtml
https://github.com/Sitefinity/feather/issues/1970
=> Language selector detail view fix

Bootstrap/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, Foundation/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, SemanticUI/MVC/Views/ImageGallery/Detail.DetailPage.cshtml
=> added comments in ImageGallery details

Bootstrap/MVC/Views/SubscribeForm/SubscribeForm.cshtml
=> Added Subscribe widget template

Bootstrap/MVC/Views/SubscribeForm/SubscribeForm.cshtml
=> Subscribe widget styles

Bootstrap/MVC/Views/SubscribeForm/SubscribeForm.cshtml
=> Changed warning message

Bootstrap/MVC/Views/SubscribeForm/SubscribeForm.cshtml, Bootstrap/MVC/Views/UnsubscribeForm/UnsubscribeFormByEmailAddress.UnsubscribeForm.cshtml, Bootstrap/MVC/Views/UnsubscribeForm/UnsubscribeFormByLink.UnsubscribeMessage.cshtml
=> Changes to front-end templates of subscribe and unsubscribe widgets

Bootstrap/MVC/Views/SubscribeForm/SubscribeForm.SubscribeForm.cshtml
=> Subscribe css

Bootstrap/MVC/Views/UnsubscribeForm/UnsubscribeFormByEmailAddress.UnsubscribeForm.cshtml
https://github.com/Sitefinity/feather-widgets/issues/1310
=> Fixed bug 1310: Unsubscribe: Messages are not styled

Bootstrap/client-components/fields/html-field/sf-html-field.sf-cshtml, Foundation/client-components/fields/html-field/sf-html-field.sf-cshtml, SemanticUI/client-components/fields/html-field/sf-html-field.sf-cshtml
=> Html field change config

Bootstrap/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/Layouts/default.cshtml
=> Extracted helper to determine if inline editing should be rendered.

Bootstrap/MVC/Views/SearchBox/SearchBox.cshtml, Foundation/MVC/Views/SearchBox/SearchBox.cshtml, SemanticUI/MVC/Views/SearchBox/SearchBox.cshtml
=> Fixed search box script issue

Bootstrap/MVC/Views/Layouts/default.cshtml, Bootstrap/MVC/Views/SearchBox/SearchBox.cshtml, Bootstrap/MVC/Views/SearchResults/SearchResults.cshtml, Foundation/MVC/Views/SearchBox/SearchBox.cshtml, Foundation/MVC/Views/SearchResults/SearchResults.cshtml, SemanticUI/MVC/Views/SearchBox/SearchBox.cshtml, SemanticUI/MVC/Views/SearchResults/SearchResults.cshtml
=> Added reference to jquery in search widgets

Bootstrap/MVC/Views/Layouts/1 Column Header Footer.cshtml, Bootstrap/MVC/Views/Layouts/2 Equal Columns Header Footer.cshtml, Bootstrap/MVC/Views/Layouts/3 Equal Columns Header Footer.cshtml, Bootstrap/MVC/Views/Layouts/4 Equal Columns Header Footer.cshtml, Bootstrap/MVC/Views/Layouts/Basic.cshtml, Bootstrap/MVC/Views/Layouts/Left Sidebar Header Footer.cshtml, Bootstrap/MVC/Views/Layouts/Right Sidebar Header Footer.cshtml
=> Added default templates for Bootstrap package

Bootstrap/GridSystem/Templates/container.html, Bootstrap/GridSystem/Templates/grid-12.html, Bootstrap/GridSystem/Templates/grid-2+3+2+3+2.html, Bootstrap/GridSystem/Templates/grid-3+3+3+3.html, Bootstrap/GridSystem/Templates/grid-3+6+3.html, Bootstrap/GridSystem/Templates/grid-3+9.html, Bootstrap/GridSystem/Templates/grid-4+4+4.html, Bootstrap/GridSystem/Templates/grid-4+8.html, Bootstrap/GridSystem/Templates/grid-6+6.html, Bootstrap/GridSystem/Templates/grid-8+4.html, Bootstrap/GridSystem/Templates/grid-9+3.html
=> Added labels to Bootstrap grid widgets

Bootstrap/client-components/fields/html-field/sf-html-field.sf-cshtml, Foundation/client-components/fields/html-field/sf-html-field.sf-cshtml, SemanticUI/client-components/fields/html-field/sf-html-field.sf-cshtml
=> Added name to the kendo editor

Bootstrap/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, SemanticUI/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml
=> Added query params to login form post

Bootstrap/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShare.cshtml, Foundation/MVC/Views/SocialShare/SocialShare.cshtml, SemanticUI/MVC/Views/LoginForm/LoginForm.LoginForm.cshtml, SemanticUI/MVC/Views/SocialShare/SocialShare.cshtml
=> Fixloginformpost

Bootstrap/MVC/Views/TextField/Read.Default.cshtml, Bootstrap/MVC/Views/TextField/Write.Default.cshtml
=> Added Read And Write templates of textField

Bootstrap/MVC/Views/SubmitButton/Index.Default.cshtml
=> Forms widget styling

Bootstrap/MVC/Views/CheckboxesField/Read.Default.cshtml, Bootstrap/MVC/Views/CheckboxesField/Write.Default.cshtml, Bootstrap/MVC/Views/CheckboxesField/Write.Default_Inline.cshtml
=> Added front-end templates for Checkboxes widget in Bootsrap

Bootstrap/MVC/Views/MultipleChoiceField/Read.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Write.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Write.Default_Inline.cshtml
=> Added Bootstrap front-end templates of Multichoice field

Bootstrap/MVC/Views/CheckboxesField/Write.Default.cshtml, Bootstrap/MVC/Views/CheckboxesField/Write.Default_Inline.cshtml
=> Fixed validation for required checkboxes

Foundation/GridSystem/Templates/container.html, Foundation/GridSystem/Templates/grid-12.html, Foundation/GridSystem/Templates/grid-2+3+2+3+2.html, Foundation/GridSystem/Templates/grid-3+3+3+3.html, Foundation/GridSystem/Templates/grid-3+6+3.html, Foundation/GridSystem/Templates/grid-3+9.html, Foundation/GridSystem/Templates/grid-4+4+4.html, Foundation/GridSystem/Templates/grid-4+8.html, Foundation/GridSystem/Templates/grid-6+6.html, Foundation/GridSystem/Templates/grid-8+4.html, Foundation/GridSystem/Templates/grid-9+3.html, SemanticUI/GridSystem/Templates/container.html, SemanticUI/GridSystem/Templates/grid-12.html, SemanticUI/GridSystem/Templates/grid-2+3+2+3+2.html, SemanticUI/GridSystem/Templates/grid-3+3+3+3.html, SemanticUI/GridSystem/Templates/grid-3+6+3.html, SemanticUI/GridSystem/Templates/grid-3+9.html, SemanticUI/GridSystem/Templates/grid-4+4+4.html, SemanticUI/GridSystem/Templates/grid-4+8.html, SemanticUI/GridSystem/Templates/grid-6+6.html, SemanticUI/GridSystem/Templates/grid-8+4.html, SemanticUI/GridSystem/Templates/grid-9+3.html
=> Add grid labels

Bootstrap/MVC/Views/TextField/Write.Default.cshtml
=> Fix violation messages in text field

Bootstrap/MVC/Views/DropdownListField/Read.Default.cshtml, Bootstrap/MVC/Views/DropdownListField/Write.Default.cshtml
=> Beta82peleva

Bootstrap/MVC/Views/FileField/Write.Default.cshtml
=> Added warning message

Bootstrap/MVC/Views/Recaptcha/Write.Default.cshtml
=> [forms-recap] - bootstrap template for recaptcha field

Bootstrap/MVC/Views/ParagraphTextField/Read.Default.cshtml, Bootstrap/MVC/Views/ParagraphTextField/Write.Default.cshtml
=> [beta82-pf] - add paragraph field to Bootstrap package

Bootstrap/MVC/Views/Engagement/Engagement.Card.cshtml, Bootstrap/MVC/Views/Engagement/Engagement.Hero.cshtml, Bootstrap/MVC/Views/Engagement/Engagement.Simple.cshtml
=> [engagement] - add templates for ex engagement widget

Bootstrap/MVC/Views/CheckboxesField/Write.Default.cshtml, Bootstrap/MVC/Views/CheckboxesField/Write.Default_Inline.cshtml, Bootstrap/MVC/Views/DropdownListField/Write.Default.cshtml, Bootstrap/MVC/Views/FileField/Write.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Write.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Write.Default_Inline.cshtml, Bootstrap/MVC/Views/ParagraphTextField/Write.Default.cshtml, Bootstrap/MVC/Views/TextField/Write.Default.cshtml
=> Hiding description field if empty

Bootstrap/MVC/Views/Captcha/Write.Default.cshtml, Bootstrap/MVC/Views/DropdownListField/Write.Default.cshtml, Bootstrap/MVC/Views/TextField/Write.Default.cshtml
=> forms unique ids

Bootstrap/MVC/Views/Card/Card.Hero.cshtml, Bootstrap/MVC/Views/Card/Card.Simple.cshtml, Bootstrap/MVC/Views/Card/Card.cshtml
=> Fixing bug #171474 - Feather: Card widget doesn't work with MVC page.

Bootstrap/MVC/Views/Card/Card.Hero.cshtml, Bootstrap/MVC/Views/Card/Card.Simple.cshtml, Bootstrap/MVC/Views/Card/Card.cshtml
=> Added ImageTitle and ImageAlternativeText to the CardViewModel.

Bootstrap/MVC/Views/FileField/Write.Default.cshtml, Bootstrap/MVC/Views/ParagraphTextField/Write.Default.cshtml
=> Peleva master

Bootstrap/MVC/Views/Card/Card.Hero.cshtml, Bootstrap/MVC/Views/Card/Card.Simple.cshtml
=> card adjustments

Bootstrap/MVC/Views/CheckboxesField/Write.Default.cshtml, Bootstrap/MVC/Views/CheckboxesField/Write.Default_Inline.cshtml
=> Fix dependency between required and default checkbox

Bootstrap/MVC/Views/Layouts/default.cshtml, Foundation/MVC/Views/Layouts/default.cshtml, SemanticUI/MVC/Views/Layouts/default.cshtml
=> Changed url helper for resolving styles url

Bootstrap/MVC/Views/SubmitButton/Write.Default.cshtml
=> Added new script to the view

Bootstrap/MVC/Views/CheckboxesField/Write.Default.cshtml, Bootstrap/MVC/Views/CheckboxesField/Write.Default_Inline.cshtml, Bootstrap/MVC/Views/DropdownListField/Read.Default.cshtml, Bootstrap/MVC/Views/DropdownListField/Write.Default.cshtml, Bootstrap/MVC/Views/FileField/Write.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Read.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Write.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Write.Default_Inline.cshtml, Bootstrap/MVC/Views/ParagraphTextField/Write.Default.cshtml
wrong Bootstrap classes used in views
=> Fix for reported issue #239

Bootstrap/MVC/Views/SubmitButton/Write.Default.cshtml
=> Added missing jQuery refernce

Bootstrap/MVC/Views/SubmitButton/Write.Default.cshtml
=> Added previous button to Submit button

Bootstrap/MVC/Views/LoginStatus/LoginStatus.LoginButton.cshtml, Bootstrap/MVC/Views/LoginStatus/LoginStatus.LoginName.cshtml, SemanticUI/MVC/Views/LoginStatus/LoginStatus.LoginButton.cshtml, SemanticUI/MVC/Views/LoginStatus/LoginStatus.LoginName.cshtml
=> login status update

Bootstrap/MVC/Views/PageBreak/Read.Default.cshtml, Bootstrap/MVC/Views/SubmitButton/Write.Default.cshtml
=> Added read template for page break

Bootstrap/MVC/Views/PageBreak/Read.Default.cshtml
=> #175284 Multipage form is looking strange on Bootstrap based page.

Bootstrap/MVC/Views/Card/Card.Hero.cshtml
=> Closed <div> tag

Bootstrap/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Fixed registration widget submit when another user widget on page

Bootstrap/razorgenerator.directives, Foundation/razorgenerator.directives, SemanticUI/razorgenerator.directives
=> View precompilation

LICENSE.md, README.md
=> Updated readme and license copyright year

LICENSE.md, README.md
=> Updated copyright info

Minimal/MVC/Views/Captcha/Write.Default.cshtml, Minimal/MVC/Views/CheckboxesField/Read.Default.cshtml, Minimal/MVC/Views/CheckboxesField/Write.Default.cshtml, Minimal/MVC/Views/CheckboxesField/Write.Default_Inline.cshtml, Minimal/MVC/Views/DropdownListField/Read.Default.cshtml, Minimal/MVC/Views/DropdownListField/Write.Default.cshtml, Minimal/MVC/Views/FileField/Write.Default.cshtml, Minimal/MVC/Views/Form/Index.cshtml, Minimal/MVC/Views/ImageGallery/List.ImageGallery.cshtml, Minimal/MVC/Views/LanguageSelector/LanguageSelector.DropDownMenu.cshtml, Minimal/MVC/Views/LanguageSelector/LanguageSelector.LanguageLinks.cshtml, Minimal/MVC/Views/MultipleChoiceField/Read.Default.cshtml, Minimal/MVC/Views/MultipleChoiceField/Write.Default.cshtml, Minimal/MVC/Views/MultipleChoiceField/Write.Default_Inline.cshtml, Minimal/MVC/Views/NavigationField/Read.Default.cshtml, Minimal/MVC/Views/NavigationField/Read.ProgressBar.cshtml, Minimal/MVC/Views/PageBreak/Read.Default.cshtml, Minimal/MVC/Views/ParagraphTextField/Read.Default.cshtml, Minimal/MVC/Views/ParagraphTextField/Write.Default.cshtml, Minimal/MVC/Views/SectionHeader/Read.Default.cshtml, Minimal/MVC/Views/SubmitButton/Write.Default.cshtml, Minimal/MVC/Views/TextField/Read.Default.cshtml, Minimal/MVC/Views/TextField/Write.Default.cshtml, Minimal/MVC/Views/VideoGallery/List.VideoGallery.cshtml
=> Precompiled minimal package

Minimal/MVC/Views/Layouts/default.cshtml
=> Added css ref

Bootstrap/client-components/fields/html-field/sf-html-field.sf-cshtml, community-packages/Foundation/client-components/fields/html-field/sf-html-field.sf-cshtml, community-packages/SemanticUI/client-components/fields/html-field/sf-html-field.sf-cshtml
=> fix html editor tools

Bootstrap/MVC/Views/ContentBlock/Default.cshtml, Minimal/MVC/Views/ContentBlock/Default.cshtml, community-packages/Foundation/MVC/Views/ContentBlock/Default.cshtml, community-packages/SemanticUI/MVC/Views/ContentBlock/Default.cshtml
=> Adding css class for the content block widget wrapper element

Bootstrap/MVC/Views/ContentBlock/Default.cshtml, Minimal/MVC/Views/ContentBlock/Default.cshtml, community-packages/Foundation/MVC/Views/ContentBlock/Default.cshtml, community-packages/SemanticUI/MVC/Views/ContentBlock/Default.cshtml
Reverts Sitefinity/feather-packages#285
=> Revert "Adding css class for the content block widget wrapper element"

Minimal/MVC/Views/Event/Detail.Default.cshtml
=> Fixed razor view errors

Bootstrap/MVC/Views/Profile/Edit.ProfileEdit.cshtml, Bootstrap/MVC/Views/Registration/Registration.RegistrationForm.cshtml, community-packages/SemanticUI/MVC/Views/Profile/Edit.ProfileEdit.cshtml, community-packages/SemanticUI/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Preventing submit in preview and design mode

Bootstrap/MVC/Views/Profile/Edit.ProfileEdit.cshtml, Bootstrap/MVC/Views/Registration/Registration.RegistrationForm.cshtml, community-packages/SemanticUI/MVC/Views/Profile/Edit.ProfileEdit.cshtml, community-packages/SemanticUI/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Preview mode submit

Bootstrap/MVC/Views/Navigation/NavigationView.Pills.cshtml
=> Added missing script

Minimal/MVC/Views/Profile/Edit.ProfileEdit.cshtml, Minimal/MVC/Views/Registration/Registration.RegistrationForm.cshtml
=> Submit changes in preview and design mode

Bootstrap/MVC/Views/EventScheduler/Detail.EventDetails.cshtml, Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/EventScheduler/Detail.EventDetails.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml
=> Added new widget 'Calendar'

Bootstrap/MVC/Views/BlogPost/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/ContentBlock/Default.cshtml, Bootstrap/MVC/Views/DocumentsList/Detail.DocumentDetails.cshtml, Bootstrap/MVC/Views/Event/Detail.EventDetails.cshtml, Bootstrap/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/Lists/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/News/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShare.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShareIconsWithText.cshtml, Bootstrap/MVC/Views/VideoGallery/Detail.Default.cshtml
=> Bug #198401 : Feather: SocialShare - LinkedIn and GooglePlus - not resolving detail page title in MVC Widgets

Bootstrap/MVC/Views/BlogPost/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/ContentBlock/Default.cshtml, Bootstrap/MVC/Views/DocumentsList/Detail.DocumentDetails.cshtml, Bootstrap/MVC/Views/Event/Detail.EventDetails.cshtml, Bootstrap/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/Lists/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/News/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShare.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShareIconsWithText.cshtml, Bootstrap/MVC/Views/VideoGallery/Detail.Default.cshtml
=> Revert "Bug #198401 : Feather: SocialShare - LinkedIn and GooglePlus - not resolving detail page title in MVC Widgets"

Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml
=> Added new properties for event scheduler widget

Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml
=> Added support for ListCssClass

Bootstrap/MVC/Views/EventScheduler/Detail.EventDetails.cshtml
=> Update details view with latest fixes

Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml
=> View changes based on security report

Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml
=> Added new attribute - current site

Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml
=> Removed duplicate attribute, change resource registration to not throw an exception

Bootstrap/MVC/Views/SocialShare/SocialShare.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShareIconsWithText.cshtml
=> #1969 - Adding the changes of Social share views to packages

Bootstrap/MVC/Views/SocialShare/SocialShare.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShareIconsWithText.cshtml
Change is related to commit in feather-widgets #1969 - Fixing GooglePlusOne not sending requests to DEC; Tmblr opening on on the same page; fixing social widget UI test
=> Adding social share view changes to bootstrap templates

Bootstrap/MVC/Views/Captcha/Write.Default.cshtml, Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Bootstrap/MVC/Views/TextField/Write.Default.cshtml, Minimal/MVC/Views/Captcha/Write.Default.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/TextField/Write.Default.cshtml
=> Code base integration team4

Bootstrap/MVC/Scripts/Navigation/pills.js, Bootstrap/MVC/Views/Navigation/NavigationView.Pills.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShare.cshtml, Bootstrap/MVC/Views/SocialShare/SocialShareIconsWithText.cshtml
=> Merge dbp to cb

Bootstrap/MVC/Views/EventScheduler/List.Calendar.cshtml, Minimal/MVC/Views/EventScheduler/List.Calendar.cshtml
=> fix calendar special char isuues

Bootstrap/MVC/Views/SearchResults/SearchResults.cshtml, Minimal/MVC/Views/SearchResults/SearchResults.cshtml, community-packages/Foundation/MVC/Views/SearchResults/SearchResults.cshtml, community-packages/SemanticUI/MVC/Views/SearchResults/SearchResults.cshtml
=> Search results can be filtered by permissions

Minimal/MVC/Views/Form/Index.cshtml
=> Fixed ajax submit in wrong form

Bootstrap/MVC/Views/LanguageSelector/LanguageSelector.DropDownMenu.cshtml
=> Added missing script for MVC Language Selector

Bootstrap/MVC/Views/LanguageSelector/LanguageSelector.DropDownMenu.cshtml
=> Added missing namespace

Bootstrap/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, Bootstrap/MVC/Views/ImageGallery/List.ImageGallery.cshtml, Bootstrap/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, Bootstrap/MVC/Views/ImageGallery/List.SimpleList.cshtml, Bootstrap/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml, Minimal/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, Minimal/MVC/Views/ImageGallery/List.ImageGallery.cshtml, Minimal/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, Minimal/MVC/Views/ImageGallery/List.SimpleList.cshtml, Minimal/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml, community-packages/Foundation/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, community-packages/Foundation/MVC/Views/ImageGallery/List.ImageGallery.cshtml, community-packages/Foundation/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, community-packages/Foundation/MVC/Views/ImageGallery/List.SimpleList.cshtml, community-packages/Foundation/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml, community-packages/SemanticUI/MVC/Views/ImageGallery/Detail.DetailPage.cshtml, community-packages/SemanticUI/MVC/Views/ImageGallery/List.ImageGallery.cshtml, community-packages/SemanticUI/MVC/Views/ImageGallery/List.OverlayGallery.cshtml, community-packages/SemanticUI/MVC/Views/ImageGallery/List.SimpleList.cshtml, community-packages/SemanticUI/MVC/Views/ImageGallery/List.ThumbnailStrip.cshtml
Fix for bug #212206: SVG images are not displayed properly in Image Gallery Overlay/Thumbain Strip
=> Fix bug: SVG images are not displayed properly in Image Gallery Overlay/Thumbain Strip

Bootstrap/MVC/Views/MultipleChoiceField/Write.Default.cshtml, Bootstrap/MVC/Views/MultipleChoiceField/Write.Default_Inline.cshtml, Minimal/MVC/Views/MultipleChoiceField/Write.Default.cshtml, Minimal/MVC/Views/MultipleChoiceField/Write.Default_Inline.cshtml
Reverts Sitefinity/feather-packages#369
=> Revert "Bug fix - #198862 - Submitting a form causes an error"
